// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CreateAlbumData, CreateAlbumError, CreateAlbumResponse, ReadAlbumsData, ReadAlbumsError, ReadAlbumsResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create Album
 */
export const createAlbum = <ThrowOnError extends boolean = false>(options: Options<CreateAlbumData, ThrowOnError>) => { return (options?.client ?? client).post<CreateAlbumResponse, CreateAlbumError, ThrowOnError>({
    ...options,
    url: '/albums/'
}); };

/**
 * Read Albums
 */
export const readAlbums = <ThrowOnError extends boolean = false>(options?: Options<ReadAlbumsData, ThrowOnError>) => { return (options?.client ?? client).get<ReadAlbumsResponse, ReadAlbumsError, ThrowOnError>({
    ...options,
    url: '/albums/'
}); };